"""Create messages table

Revision ID: 1c3842e9e323
Revises: 0f3aef6ab836
Create Date: 2025-06-14 12:55:02.664164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3842e9e323'
down_revision = '0f3aef6ab836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
